name: 'healthcare_claims'

version: '1.0'

config-version: 2

profile: 'healthcare_claims'


model-paths: ["models"]

analysis-paths: ["analyses"]

test-paths: ["tests"]

seed-paths: ["seeds"]

macro-paths: ["macros"]

snapshot-paths: ["snapshots"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"



models:

  healthcare_claims:

    staging:

      +materialized: view

      # +schema: RAW


    intermediate:

      +materialized: incremental

      +schema: STRUCTURED


    # marts:

    #   +materialized: table

    #   +schema: ANALYTICS